baseURL = "https://1minutedanceparty.com/"
title = "1minutedanceparty"
name = "1minutedanceparty"
license = "MIT"
licenselink = "https://github.com/.../.../LICENSE.md"
homepage = "https://konigi.com/"
description = ""
tags = ["1minutedanceparty", "blog"]
features = ["sections", "pages", "summaries", "href", "featuredimg"]

[author]
  name = "Michael Angeles"
